-- 订阅计划表
create table if not exists subscription_plans
(
    id            bigint generated by default as identity primary key,
    created_at    timestamp with time zone default now() not null,
    updated_at    timestamp with time zone default now() not null,
    plan_id       varchar unique not null,
    name          varchar not null,
    price         decimal(10,2) not null,
    currency      varchar(3) default 'USD' not null,
    interval_type varchar(10) default 'month' not null, -- month, year
    daily_limit   integer not null,
    features      jsonb,
    is_active     boolean default true not null
);

comment on table subscription_plans is '订阅计划表';
comment on column subscription_plans.plan_id is '计划唯一标识';
comment on column subscription_plans.name is '计划名称';
comment on column subscription_plans.price is '价格';
comment on column subscription_plans.currency is '货币代码';
comment on column subscription_plans.interval_type is '计费周期：month/year';
comment on column subscription_plans.daily_limit is '每日使用限制';
comment on column subscription_plans.features is '功能特性JSON';
comment on column subscription_plans.is_active is '是否激活';

-- 插入默认计划
insert into subscription_plans (plan_id, name, price, daily_limit, features) values
('free', 'Free', 0.00, 20, '{"support": "community", "priority": "normal"}'),
('premium', 'Premium', 9.99, 50, '{"support": "priority", "priority": "high", "advanced_features": true}')
on conflict (plan_id) do nothing;