-- 用户订阅表
create table if not exists user_subscriptions
(
    id                 bigint generated by default as identity primary key,
    created_at         timestamp with time zone default now() not null,
    updated_at         timestamp with time zone default now() not null,
    user_id            varchar not null,
    plan_id            varchar not null,
    creem_subscription_id varchar,
    status             varchar(20) default 'active' not null, -- active, cancelled, expired, pending
    current_period_start timestamp with time zone,
    current_period_end   timestamp with time zone,
    cancel_at_period_end boolean default false not null,
    trial_start        timestamp with time zone,
    trial_end          timestamp with time zone,
    metadata           jsonb
);

comment on table user_subscriptions is '用户订阅表';
comment on column user_subscriptions.user_id is '用户ID';
comment on column user_subscriptions.plan_id is '订阅计划ID';
comment on column user_subscriptions.creem_subscription_id is 'Creem订阅ID';
comment on column user_subscriptions.status is '订阅状态';
comment on column user_subscriptions.current_period_start is '当前周期开始时间';
comment on column user_subscriptions.current_period_end is '当前周期结束时间';
comment on column user_subscriptions.cancel_at_period_end is '是否在周期结束时取消';
comment on column user_subscriptions.trial_start is '试用开始时间';
comment on column user_subscriptions.trial_end is '试用结束时间';
comment on column user_subscriptions.metadata is '元数据';

-- 创建索引
create index if not exists idx_user_subscriptions_user_id on user_subscriptions(user_id);
create index if not exists idx_user_subscriptions_status on user_subscriptions(status);
create index if not exists idx_user_subscriptions_creem_id on user_subscriptions(creem_subscription_id);