-- 每日使用统计表
create table if not exists daily_usage
(
    id         bigint generated by default as identity primary key,
    created_at timestamp with time zone default now() not null,
    updated_at timestamp with time zone default now() not null,
    user_id    varchar,
    ip_address inet,
    usage_date date default current_date not null,
    usage_count integer default 0 not null,
    user_type  varchar(20) default 'guest' not null -- guest, free, premium
);

comment on table daily_usage is '每日使用统计表';
comment on column daily_usage.user_id is '用户ID（可为空，表示未登录用户）';
comment on column daily_usage.ip_address is 'IP地址（用于未登录用户计数）';
comment on column daily_usage.usage_date is '使用日期';
comment on column daily_usage.usage_count is '使用次数';
comment on column daily_usage.user_type is '用户类型：guest/free/premium';

-- 创建复合索引
create unique index if not exists idx_daily_usage_user_date on daily_usage(user_id, usage_date) where user_id is not null;
create unique index if not exists idx_daily_usage_ip_date on daily_usage(ip_address, usage_date) where user_id is null;
create index if not exists idx_daily_usage_date on daily_usage(usage_date);