-- 支付记录表
create table if not exists payment_records
(
    id                bigint generated by default as identity primary key,
    created_at        timestamp with time zone default now() not null,
    updated_at        timestamp with time zone default now() not null,
    user_id           varchar not null,
    creem_payment_id  varchar unique,
    subscription_id   bigint references user_subscriptions(id),
    amount            decimal(10,2) not null,
    currency          varchar(3) default 'USD' not null,
    status            varchar(20) default 'pending' not null, -- pending, completed, failed, refunded
    payment_method    varchar(50),
    failure_reason    text,
    metadata          jsonb
);

comment on table payment_records is '支付记录表';
comment on column payment_records.user_id is '用户ID';
comment on column payment_records.creem_payment_id is 'Creem支付ID';
comment on column payment_records.subscription_id is '关联订阅ID';
comment on column payment_records.amount is '支付金额';
comment on column payment_records.currency is '货币代码';
comment on column payment_records.status is '支付状态';
comment on column payment_records.payment_method is '支付方式';
comment on column payment_records.failure_reason is '失败原因';
comment on column payment_records.metadata is '元数据';

-- 创建索引
create index if not exists idx_payment_records_user_id on payment_records(user_id);
create index if not exists idx_payment_records_status on payment_records(status);
create index if not exists idx_payment_records_creem_id on payment_records(creem_payment_id);